id: A99D34A96
title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö and Khandro Tsering
  Chödrön
type: translation
pechas:
- IBC6FB18F
- IC8E8D2FD
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:15:44.420500
  last_modified_at: 2023-01-04 12:15:44.420512
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IBC6FB18F/E0AC: 4B0E
  IC8E8D2FD/A879: 4B0E
